package gdiclab.wqesa;
import javax.swing.*; // подключение всех компонентов и интерфейсов из пакета 
import java.awt.*;/* подключение всех кл-в и интерфейсов из п.java.awt */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Math.sqrt;
import java.text.DecimalFormat;// импорт класса DecimalFormat

public class WQesa extends JFrame{

//объявление переменных 
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JTextField jTextField1;
    private JTextField jTextField2;
    private JTextField jTextField3;
    private JTextField jTextField4;
    private JTextField jTextField5;
    private JTextField jTextField6;
    private JTextField jTextField7;
        
/*метод initComponents() вызывается внутри констр-ра для иниц-ции всех 
созданных комп-тов GUI, к.были созданы с помощью GUI Builder в NetBeans.*/
    public WQesa() {
        initComponents();
    }
    
    //*** This method is called from within the constructor to initialize the form.
    //* WARNING: Do NOT modify this code. The content of this method is always
    //* regenerated by the Form Editor*/
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
//создание объектов классов

//создание компонентов окна
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jTextField1 = new JTextField(10);
        jTextField1.setFont(new Font("monospaced",Font.BOLD, 16));
        jTextField1.setForeground(Color.green);
        jTextField1.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel2 = new JLabel();
        jTextField2 = new JTextField(10);
        jTextField2.setFont(new Font("monospaced",Font.BOLD, 16));
        jTextField2.setForeground(Color.green);
        jTextField2.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel3 = new JLabel();
        jTextField3 = new JTextField(10);
        jTextField3.setFont(new Font("monospaced",Font.BOLD, 16));
        jTextField3.setForeground(Color.green);
        jTextField3.setHorizontalAlignment(SwingConstants.RIGHT);
        jButton1 = new JButton();
        jButton2 = new JButton();
        jPanel2 = new JPanel();
        jLabel4 = new JLabel();
        jTextField4 = new JTextField(10);
        jTextField4.setFont(new Font("monospaced",Font.BOLD, 16));
        jTextField4.setForeground(Color.MAGENTA);
        jTextField4.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel5 = new JLabel();
        jTextField5 = new JTextField(10);
        jTextField5.setFont(new Font("monospaced",Font.BOLD, 16));
        jTextField5.setForeground(Color.blue);
        jTextField5.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel6 = new JLabel();
        jTextField6 = new JTextField(10);
        jTextField6.setFont(new Font("monospaced",Font.BOLD, 16));
        jTextField6.setForeground(Color.blue);
        jTextField6.setHorizontalAlignment(SwingConstants.RIGHT);
        jTextField7 = new JTextField(40);
        jTextField7.setFont(new Font("monospaced",Font.BOLD, 16));
        jTextField7.setForeground(Color.red);
        jTextField7.setHorizontalAlignment(SwingConstants.RIGHT);
        jButton3 = new JButton();
        jButton4 = new JButton();
        
        setDefaultCloseOperation(EXIT_ON_CLOSE);
//вызов метода createTitledBorder класса BorderFactory 
        jPanel1.setBorder(BorderFactory.createTitledBorder("Поле ввода коэффициентов кв. уравнения ax^x+bx+c=0"));

        jLabel1.setText("Коэффициент а (a!=0)");

        jLabel2.setText("Коэффициент b");

        jLabel3.setText("Коэффициент c");

        jButton1.setText("Расчет");
        /*для комп-та jButton1 регистрируем универс. слушателем ActionListener 
        методом addActionListener() для обработки события единств.методом 
        actionPerformed(ActionEvent evt). Для остальных компонентов - аналогично*/
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Отмена");
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
                
        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(BorderFactory.createTitledBorder("Результаты"));
        jLabel4.setText("Дискриминант D");
        jLabel5.setText("Корень х1");
        jLabel6.setText("Корень х2");
        jButton3.setText("Новая задача");
        
        jButton2.setText("Отмена");
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        
        jButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
        
        jButton4.setText("Выход");
        jButton4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(12, 12, 12)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();//оптимизируем расположение компонентов в окне
    }                        

//действия при нажатии кнопки Расчет    
    private void jButton1ActionPerformed(ActionEvent evt) {                                         
// кнопка "Расчет" выполняет ряд дествий, в т.ч. определение переменных 
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        
        float a, b, c;
        double D, x1, x2;
        
        
/*принимает введенные в полях jTextField1-3 данные и преобразует их из типа 
String в тип Float*/
        
        a = Float.parseFloat(jTextField1.getText());
        b = Float.parseFloat(jTextField2.getText());
        c = Float.parseFloat(jTextField3.getText());
//вычисляем дискриминант D
        D = (b*b-4*a*c); 
//создание экз-ра dfD класса DecimalFormat с шаблоном форматирования
        DecimalFormat dfD = new DecimalFormat("#.###");
//форматируем число с преобразованием D из типа double в string перед выводом в JTextField 
        String formattedD = dfD.format(D);
//и устанавливаем его в текстовое поле
        jTextField4.setText(formattedD);
        //jTextField4.setText(String.valueOf(D));//старое выражение 
		
//если D>0 определяем корни
        if  (D>0){
        x1 = (-b - sqrt(D))/(2*a);
        x2 = (-b + sqrt(D))/(2*a);
		
//очищаем поле для случая исправления ввода без кнопки Отмена
        jTextField7.setText("");
//создаем экз-р dfx1 класса DecimalFormat с шаблоном форматирования
        DecimalFormat dfx1 = new DecimalFormat("#.###");
//форматируем число с преобразованием х1 из типа double в string перед выводом в JTextField5
        String formattedX1 = dfx1.format(x1);
//и устанавливаем его в текстовое поле        
        jTextField5.setText(formattedX1);
        //jTextField5.setText(String.valueOf(x1));//старое выражение
		
//создание экз-ра dfx2 класса DecimalFormat с шаблоном форматирования        
        DecimalFormat df2 = new DecimalFormat("#.###");
//форматируем число с преобразованием х1 из типа double в string перед выводом в JTextField6        
        String formattedX2 = df2.format(x2);
//и устанавливаем его в текстовое поле      
        jTextField6.setText(formattedX2);
        //jTextField6.setText(String.valueOf(x2));//старое выражение 
		}
//если D<0 сообщает в текст.поле об отсутствии действ.корней  
        else if(D<0){
        jTextField7.setText("Действительные корни отсутствуют");
        }
//если D=0 определяет корни х1=х2 
        else{
        x1=-b/(2*a);
        x2=x1;
//очищаем поле для случая исправления ввода без кнопки Отмена
        jTextField7.setText("");
//создаем экз-р dfx1 класса DecimalFormat с шаблоном форматирования
        DecimalFormat dfx1 = new DecimalFormat("#.###");
//форматируем число с преобразованием х1 из типа double в string перед выводом в JTextField5
        String formattedX1 = dfx1.format(x1);
//и устанавливаем его в текстовое поле        
        jTextField5.setText(formattedX1);
        jTextField6.setText(formattedX1);

        //jTextField5.setText(String.valueOf(x1));//старое выражение
        //jTextField6.setText(String.valueOf(x2));//старое выражение
        }
    }           
//действия при нажатии кнопки Отмена    
    private void jButton2ActionPerformed(ActionEvent evt) {                                         
//очистка текстовых полей ввода к-тов a, b, c
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        }                                        
//действия при нажатии кнопки Новая задача
    private void jButton3ActionPerformed(ActionEvent evt) {                                         
//очистка текст.полей вывода рез-тов (D, x1, x2, сообщ.об отсутствии действ.корней)
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        }                                        
//действия при нажатии кнопки Выход (выход из приложения)
    private void jButton4ActionPerformed(ActionEvent evt) {
        System.exit(0);
    	}                                        

    public static void main(String args[]) {
// Создание и отображение формы
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                WQesa wqesa = new WQesa();
// Инициализация компонентов, вместо new WQesa() можно указать wqesa                
		 new WQesa().initComponents(); 
//установка видимости - new WQesa()нельзя заменить на wqesa
                 new WQesa().setVisible(true);
            }
        });
    }
}
